name: tibetan_language_learning_app
description: Tibetan Language Learning App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+20

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_animations: 1.0.0
  painter: 2.0.0
  cupertino_icons: 1.0.5
  flutter_colorpicker: ^1.1.0
  just_audio: ^0.9.40
  flutter_bloc: 8.0.1
  url_launcher: 6.1.5
  share_plus: ^10.0.2
  animated_text_kit: 4.2.2
  google_mobile_ads: ^5.1.0
  get_it: 7.2.0
  equatable: 2.0.3
  firebase_crashlytics: ^4.1.2
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2
  shared_preferences: 2.0.15
  provider:
  liquid_progress_indicator_v2: ^0.5.0
  confetti: ^0.7.0
  carousel_slider: ^5.0.0
  lottie: 1.3.0

  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
flutter_icons:
  image_path: "assets/images/ic_launcher.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#57612F"
  image: assets/images/splash.png
  fullscreen: true
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/words/
    - assets/audio/colors/
    - assets/audio/family/
    - assets/audio/greeting/
    - assets/audio/number/
    - assets/audio/pronoun/
    - assets/others/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: jomolhari
      fonts:
        - asset: assets/fonts/jomolhari-regular.ttf
    - family: tsutong
      fonts:
        - asset: assets/fonts/qomolangma-tsutong.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
